FROM python:3.9

WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app/flask_app
COPY ./Webserver-main/images /app/flask_app/Webserver-main/images
CMD ["python", "flask_app/app.py"]
