version: '3.8'

services:
  web:
    build: .
    ports:
      - "10100:5000"
    environment:
      FLASK_ENV: production
      MYSQL_HOST: db
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password
      MYSQL_DATABASE: flask_app
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

  db:
    image: mysql:8.0.34  # Specify a specific version
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: flask_app
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: flask_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Uncommented init.sql
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -prootpassword || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 200s

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge
